export const name_ciudades:  string[] = [
    'Pillaro',
    'Cuenca',
    'Machala',
    'Duran',
    'Portoviejo',
    'Manta',
    'Loja',
    'Ambato',
    'Esmeralda',
    'Quevedo',
    'Riobamba',
    'Ibarra',
    'Latacunga',
    'Babahoyo',
    'La Libertdad',
    'Daule',
    'Sangolqui',
    'Tucal',
    'Chone',
    'Pasaje',
    'Santa Rosa',
    'Nueva Loja',
    'Huaquillas',
    'El Carmen',
    'Montecristi',
    'Samborondon',
    'Jipijapa',
    'Guayaquil', 
    'Santa Elena',
    'Otavalo',
    'Cayambe',
    'Ventanas',
    'La Troncal',
    'El Triunfo',
    'Salinas',
    'Azogues',
    'Puyo',
    'Vinces',
    'La Concordia',
    'Batzar',
    'Naranjito',
    'Naranjal',
    'Guaranda',
    'Tena',
    'Santo Domingo',
    'San Lorenzo',
    'Catamayo',
    'Pedernales',
    'Atuntaqui',
    'Pedro Carbo',
    'Macás',
    'Yaguachi',
    'Calceta',
    'Arenillas',
    'Valencia',
    'Machachi',
    'Atacames',
    'Piñas',
    'San Gabriel',
    'Gualaceo',
    'Cañar',
    'Cariamanga',
    'Baños de Agua Santa',
    'Montalvo',
    'Macará',
    'Zamora',
    'Tabacundo',
    'Zaruma',
    'Balao',
    'Cotacachi',
    'Cumbaya',
    'Portovelo',
    'Guano',
    'Quito',
    'Paute',
    'Catacocha',
    'Alausi',
    'Catarama',
    'Caluma',
    'Junin',
    'Alamor',
    'Santa Clara'

  ];

  name_ciudades.sort()